shiro:
  realm: com.icms.config.security.MyRealm
  loginUrl: /view/sign-in.html
  successUrl: /index.html
  unauthorizedUrl: /forbidden.html
  filterChainDefinitions:
    "/login": anon
    "/view/sign-in": anon
    "/forbidden.html": anon
    "/blank.html": anon
    "/error.html": anon
    "/sign-up": anon
    "/css/**": anon
    "/static/**": anon
    "/bower_components/**": anon
    "/app/**": anon
    "/lib/**": anon
    "/auth": anon
    "/account/**": anon
    "/index.html": anon
    "/about.html": anon
    "/logout": anon
    "/": anon
    "/view/header**": anon
    "/view/**": anon
    "/post/**": anon
    "/user/create": anon
    "/user/**": authc
    "/view/admin/**": authc,roles[admin]
    "/**": authc
  enableShareJsession: true
  shareJsessionKey: SHAREJSESSIONID
  domain: .icms.com
  path: /